"""
Castelnuovo worked example for core/ifc_processing/hmo_mqi.py.

Loads resources/survey_data/castelnuovo/masonry_classification.json (the
photo/manuscript-grounded classification of the 4 IFC masonry types),
runs each through the MQI engine, and produces two outputs:

  1. output/castelnuovo/hmo_graph.ttl - an RDF/Turtle graph instantiating
     HSV (survey provenance) and HMO (masonry characterisation) individuals
     for the case study. Hand-written Turtle, not rdflib (not installed in
     this image) - simple enough that string templating is clearer than a
     dependency for it.
  2. output/castelnuovo/material_database.json - flat JSON keyed by the
     same material names the IFC file and this repo's own
     core/ifc_processing/data_extractor.py use ("Tufelli_masonry_typeA"
     etc.), in the same field shape as data_extractor.py's Material class,
     so it can be merged into that pipeline's material_db without a
     translation step. Also mirrors the "JSON database keyed by IFC GUID"
     pattern the case-study manuscript describes for the web platform -
     see resources/survey_data/castelnuovo/masonry_classification.json's
     _meta for the full provenance trail.

Only HMO is populated in real depth here. HSTO (structural decomposition -
facades, floors, unit-to-unit connections) is deliberately left minimal
(just hsto:isMadeOf, the one property confirmed directly from the
manuscript text) rather than guessing at class/property names that were
not independently verified against the ontology source the way HMO's
were - see PROJECT_BRIEF.md's own rule about not guessing.
"""
import json
import os
import sys

sys.path.insert(0, "/app")
from core.ifc_processing.hmo_mqi import MasonryObservation, evaluate

CLASSIFICATION_PATH = "resources/survey_data/castelnuovo/masonry_classification.json"
OUT_DIR = "output/castelnuovo"


def compute_all(classification):
    results = {}
    for name, t in classification["types"].items():
        obs = MasonryObservation(**t["observation"])
        r = evaluate(obs, mass_density_kg_m3=t["mass_density_kg_m3"])
        r["description"] = t["description"]
        r["evidence"] = t["evidence"]
        r["flags"] = t["flags"]
        r["ntc_comparison"] = t["ntc_comparison"]
        results[name] = r
    return results


def print_summary(results):
    """Prints fm/E/G/tau0 for eyeball comparison against the prose numbers
    in masonry_classification.json's ntc_comparison notes (computed by hand
    during the chat session before this script existed) - the notes are
    free text, not parsed here, so this is a manual cross-check, not an
    automated one.
    """
    for name, r in results.items():
        mech = r["mechanical_properties"]
        print(f"{name}: fm={mech['compressive_strength_MPa']} E={mech['young_modulus_MPa']} "
              f"G={mech['shear_modulus_MPa']} tau0={mech['shear_strength_turnsek_cacovic_MPa']}")


TTL_HEADER = """@prefix : <https://example.org/castelnuovo#> .
@prefix hsv: <https://w3id.org/hsv#> .
@prefix hsto: <https://w3id.org/hsto#> .
@prefix hmo: <https://w3id.org/hmo#> .
@prefix saref: <https://saref.etsi.org/core/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

# Castelnuovo di Porto case study - HSV/HMO instance graph.
# Generated by docker/opensees/castelnuovo_hmo_graph.py from
# resources/survey_data/castelnuovo/masonry_classification.json.
# HSTO usage is intentionally minimal - see this file's module docstring.

:CastelnuovoAggregate a hsv:Document ;
    rdfs:label "Unreinforced masonry aggregate, Castelnuovo di Porto (RM), between Piazza Garibaldi and Via Umberto I" .

:SurveyCampaign_20230601 a hsv:Document ;
    rdfs:label "On-site photographic survey, 2023-06-01" ;
    hsv:hasDocument :CastelnuovoAggregate .

:CaseStudyManuscript a hsv:Document ;
    rdfs:label "Semantic modelling of historic unreinforced masonry aggregates - case study manuscript" ;
    hsv:hasDocument :CastelnuovoAggregate .
"""


def masonry_wall_ttl(name, r):
    rve = f":{name}_RVE"
    mqi = f":{name}_MQI"
    lines = []
    lines.append(f'\n# --- {name} ---')
    lines.append(f'# {r["description"]}')
    lines.append(f'# Evidence: {r["evidence"]}')
    for flag in r["flags"]:
        lines.append(f'# Flag: {flag}')
    lines.append(f':{name} a hmo:MasonryWall ;')
    lines.append(f'    rdfs:label "{name}" ;')
    lines.append(f'    hsv:hasDocument :SurveyCampaign_20230601, :CaseStudyManuscript ;')
    lines.append(f'    hmo:hasRepresentativeVolumeElement {rve} .')
    lines.append("")
    lines.append(f'{rve} a hmo:RepresentativeVolumeElement ;')
    lines.append(f'    hmo:hasMasonryQualityIndex {mqi} ;')

    props = []
    mech = r["mechanical_properties"]
    if mech["compressive_strength_MPa"] is not None:
        props.append(("CompressiveStrength", mech["compressive_strength_MPa"], "MPa"))
    if mech["young_modulus_MPa"] is not None:
        props.append(("YoungModulus", mech["young_modulus_MPa"], "MPa"))
    if mech["shear_modulus_MPa"] is not None:
        props.append(("ShearModulus", mech["shear_modulus_MPa"], "MPa"))
    if mech["shear_strength_turnsek_cacovic_MPa"] is not None:
        props.append(("ShearStrengthTC", mech["shear_strength_turnsek_cacovic_MPa"], "MPa"))
    if mech["mass_density_kg_m3"] is not None:
        props.append(("MassDensity", mech["mass_density_kg_m3"], "kg/m3"))

    prop_refs = " ,\n        ".join(f":{name}_{pname}" for pname, _, _ in props)
    lines.append(f'    hmo:hasHomogeneisedMechanicalProperty\n        {prop_refs} .')
    lines.append("")

    mqi_total = r["mqi_total"]
    lines.append(f'{mqi} a hmo:MasonryQualityIndex ;')
    lines.append(f'    hmo:MQITotalVertical {mqi_total["vertical"]} ;')
    lines.append(f'    hmo:MQITotalOutOfPlane {mqi_total["out_of_plane"]} ;')
    lines.append(f'    hmo:MQITotalInPlane {mqi_total["in_plane"]} .')
    lines.append("")

    for pname, value, unit in props:
        lines.append(f':{name}_{pname} a hmo:{pname} ;')
        lines.append(f'    saref:hasValue {value} ;')
        lines.append(f'    saref:hasUnitOfMeasurement "{unit}" .')
        lines.append("")

    return "\n".join(lines)


def write_ttl(results, path):
    with open(path, "w", encoding="utf-8") as f:
        f.write(TTL_HEADER)
        for name, r in results.items():
            f.write(masonry_wall_ttl(name, r))


def write_material_database(results, path):
    """Field-compatible with core.ifc_processing.data_extractor.Material:
    name, density, young_modulus, poisson_ratio, is_structural,
    material_model_type, compressive_strength, tensile_strength,
    compression_fracture_energy, tensile_fracture_energy,
    compressive_elastic_behaviour.

    HMO does not derive tensile strength or fracture energies (only
    compressive strength, the two shear strengths - one of which is
    unimplemented, see hmo_mqi.py - Young's/shear modulus, and this
    script's own literature-value density). tensile_strength is left as
    None here rather than invented; compression/tensile_fracture_energy
    are left at 0, which is not a placeholder without consequence - see
    core/opensees_generation/model_builder.py's create_plastic_damage_elements,
    which already falls back to Gc = 15 + 0.43*fc - 0.0036*fc^2 and
    Gt = 0.025*(fc/10)^0.7 (Bazant, cited there) when the material's own
    values are 0. So leaving these at 0 activates an existing, deliberate
    fallback in this pipeline rather than leaving a silent gap.
    """
    db = {}
    for name, r in results.items():
        mech = r["mechanical_properties"]
        db[name] = {
            "name": name,
            "density": mech["mass_density_kg_m3"],
            "young_modulus": mech["young_modulus_MPa"],
            "poisson_ratio": 0.2,  # literature default for masonry, not MQI-derived - HMO has no rule for it
            "is_structural": True,
            "material_model_type": "PlasticDamage",
            "compressive_strength": mech["compressive_strength_MPa"],
            "tensile_strength": None,
            "compression_fracture_energy": 0,
            "tensile_fracture_energy": 0,
            "compressive_elastic_behaviour": 0,
            "_mqi_total": r["mqi_total"],
            "_shear_modulus_MPa": mech["shear_modulus_MPa"],
            "_shear_strength_turnsek_cacovic_MPa": mech["shear_strength_turnsek_cacovic_MPa"],
            "_evidence": r["evidence"],
            "_flags": r["flags"],
        }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(CLASSIFICATION_PATH) as f:
        classification = json.load(f)

    results = compute_all(classification)
    print_summary(results)

    write_ttl(results, os.path.join(OUT_DIR, "hmo_graph.ttl"))
    write_material_database(results, os.path.join(OUT_DIR, "material_database.json"))
    print(f"\nWrote {OUT_DIR}/hmo_graph.ttl and {OUT_DIR}/material_database.json")


if __name__ == "__main__":
    main()
