"""
Castelnuovo worked example for core/ifc_processing/hmo_mqi.py.

Loads resources/survey_data/castelnuovo/masonry_classification.json (the
photo/manuscript-grounded classification of the 4 IFC masonry types),
runs each through the MQI engine, and produces two outputs:

  1. output/castelnuovo/hmo_graph.ttl - an RDF/Turtle graph instantiating
     HSV (survey provenance), HSTO (structural decomposition: structural
     units, facades, quoin connections, timber floors, one historic
     opening) and HMO (masonry characterisation) individuals for the case
     study. Hand-written Turtle, not rdflib (not installed in this image)
     - simple enough that string templating is clearer than a dependency
     for it.
  2. output/castelnuovo/material_database.json - flat JSON keyed by the
     same material names the IFC file and this repo's own
     core/ifc_processing/data_extractor.py use ("Tufelli_masonry_typeA"
     etc.), in the same field shape as data_extractor.py's Material class,
     so it can be merged into that pipeline's material_db without a
     translation step (see utils.dict_helper.load_material_objects, which
     reads exactly this file). Also mirrors the "JSON database keyed by
     IFC GUID" pattern the case-study manuscript describes for the web
     platform - see
     resources/survey_data/castelnuovo/masonry_classification.json's
     _meta for the full provenance trail.

HSTO classes and properties (hsto:StructuralPart, hsto:Facade, hsto:Quoin,
hsto:TimberFloor, hsto:HistoricOpening, hsto:isMadeOf, hsto:isConnectedTo,
hsto:hasHistoricOpening) were verified against the ontology source
(github.com/mlaura1996/Historic-Structure-Ontology/blob/main/ontology.ttl,
375 lines, read in full) the same way HMO's were, rather than guessed from
the thesis prose. One real finding from reading the source: HSTO has **no**
object property linking a hsto:StructuralPart to the hsto:Facade /
hsto:HorizontalStructure instances that decompose it - composition is
presumably left to BEO/IFC spatial containment rather than duplicated in
HSTO. hsto_ttl() below records that relationship as an rdfs:comment instead
of forcing it through a property with the wrong domain/range (which would
silently produce an invalid graph) - see that function's docstring.
"""
import json
import os
import sys

sys.path.insert(0, "/app")
from core.ifc_processing.hmo_mqi import MasonryObservation, evaluate

CLASSIFICATION_PATH = "resources/survey_data/castelnuovo/masonry_classification.json"
OUT_DIR = "output/castelnuovo"


def compute_all(classification):
    results = {}
    for name, t in classification["types"].items():
        obs = MasonryObservation(**t["observation"])
        r = evaluate(obs, mass_density_kg_m3=t["mass_density_kg_m3"])
        r["description"] = t["description"]
        r["evidence"] = t["evidence"]
        r["flags"] = t["flags"]
        r["ntc_comparison"] = t["ntc_comparison"]
        results[name] = r
    return results


def print_summary(results):
    """Prints fm/E/G/tau0 for eyeball comparison against the prose numbers
    in masonry_classification.json's ntc_comparison notes (computed by hand
    during the chat session before this script existed) - the notes are
    free text, not parsed here, so this is a manual cross-check, not an
    automated one.
    """
    for name, r in results.items():
        mech = r["mechanical_properties"]
        print(f"{name}: fm={mech['compressive_strength_MPa']} E={mech['young_modulus_MPa']} "
              f"G={mech['shear_modulus_MPa']} tau0={mech['shear_strength_turnsek_cacovic_MPa']}")


TTL_HEADER = """@prefix : <https://example.org/castelnuovo#> .
@prefix hsv: <https://w3id.org/hsv#> .
@prefix hsto: <https://w3id.org/hsto#> .
@prefix hmo: <https://w3id.org/hmo#> .
@prefix saref: <https://saref.etsi.org/core/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

# Castelnuovo di Porto case study - HSV/HSTO/HMO instance graph.
# Generated by docker/opensees/castelnuovo_hmo_graph.py from
# resources/survey_data/castelnuovo/masonry_classification.json.
# HSTO classes/properties verified against the ontology source
# (github.com/mlaura1996/Historic-Structure-Ontology/blob/main/ontology.ttl,
# 375 lines, read in full) rather than guessed - see the module docstring
# for what's still inferred (unit adjacency order) vs. directly observed.

:CastelnuovoAggregate a hsv:Document ;
    rdfs:label "Unreinforced masonry aggregate, Castelnuovo di Porto (RM), between Piazza Garibaldi and Via Umberto I" .

:SurveyCampaign_20230601 a hsv:Document ;
    rdfs:label "On-site photographic survey, 2023-06-01" ;
    hsv:hasDocument :CastelnuovoAggregate .

:CaseStudyManuscript a hsv:Document ;
    rdfs:label "Semantic modelling of historic unreinforced masonry aggregates - case study manuscript" ;
    hsv:hasDocument :CastelnuovoAggregate .
"""


def masonry_wall_ttl(name, r):
    rve = f":{name}_RVE"
    mqi = f":{name}_MQI"
    lines = []
    lines.append(f'\n# --- {name} ---')
    lines.append(f'# {r["description"]}')
    lines.append(f'# Evidence: {r["evidence"]}')
    for flag in r["flags"]:
        lines.append(f'# Flag: {flag}')
    lines.append(f':{name} a hmo:MasonryWall ;')
    lines.append(f'    rdfs:label "{name}" ;')
    lines.append(f'    hsv:hasDocument :SurveyCampaign_20230601, :CaseStudyManuscript ;')
    lines.append(f'    hmo:hasRepresentativeVolumeElement {rve} .')
    lines.append("")
    lines.append(f'{rve} a hmo:RepresentativeVolumeElement ;')
    lines.append(f'    hmo:hasMasonryQualityIndex {mqi} ;')

    props = []
    mech = r["mechanical_properties"]
    if mech["compressive_strength_MPa"] is not None:
        props.append(("CompressiveStrength", mech["compressive_strength_MPa"], "MPa"))
    if mech["young_modulus_MPa"] is not None:
        props.append(("YoungModulus", mech["young_modulus_MPa"], "MPa"))
    if mech["shear_modulus_MPa"] is not None:
        props.append(("ShearModulus", mech["shear_modulus_MPa"], "MPa"))
    if mech["shear_strength_turnsek_cacovic_MPa"] is not None:
        props.append(("ShearStrengthTC", mech["shear_strength_turnsek_cacovic_MPa"], "MPa"))
    if mech["mass_density_kg_m3"] is not None:
        props.append(("MassDensity", mech["mass_density_kg_m3"], "kg/m3"))

    prop_refs = " ,\n        ".join(f":{name}_{pname}" for pname, _, _ in props)
    lines.append(f'    hmo:hasHomogeneisedMechanicalProperty\n        {prop_refs} .')
    lines.append("")

    mqi_total = r["mqi_total"]
    lines.append(f'{mqi} a hmo:MasonryQualityIndex ;')
    lines.append(f'    hmo:MQITotalVertical {mqi_total["vertical"]} ;')
    lines.append(f'    hmo:MQITotalOutOfPlane {mqi_total["out_of_plane"]} ;')
    lines.append(f'    hmo:MQITotalInPlane {mqi_total["in_plane"]} .')
    lines.append("")

    for pname, value, unit in props:
        lines.append(f':{name}_{pname} a hmo:{pname} ;')
        lines.append(f'    saref:hasValue {value} ;')
        lines.append(f'    saref:hasUnitOfMeasurement "{unit}" .')
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------
# HSTO structural decomposition - structural units, facades (each
# isMadeOf one of the 4 hmo:MasonryWall types), quoin connections, timber
# floors, one historic opening. Every fact below cites its evidence; the
# STRUCTURAL_UNITS unit-to-facade and facade-to-masonry-type mapping is
# read from the survey photo subfolder structure (A-417/417_a, 417_b,
# 417_c; A-418/418-a, 418b; A-419/a419; A-420/a420) cross-referenced
# against the classifications in masonry_classification.json (Section
# 6.2 of docs/hmo_mqi_methodology.md). The row ADJACENCY (417-418-419-420)
# is inferred from the cadastral map excerpt the user shared (parcels in
# that left-to-right order along the row between Piazza Garibaldi and Via
# Umberto I) - NOT verified against the IFC model's own touching-pair
# geometry (that check belongs to core.mesh_generation.wall_interfaces,
# a separate part of this pipeline, on the actual IFC/STEP geometry, not
# this survey-side ontology graph).
# ---------------------------------------------------------------------

STRUCTURAL_UNITS = {
    "StructuralUnit_417": {
        "facades": {
            "Facade_417a": "Tufelli_masonry_typeC",
            "Facade_417b": "Tufelli_masonry_typeD",
            "Facade_417c": "Tufelli_masonry_typeB",
        },
    },
    "StructuralUnit_418": {
        "facades": {
            "Facade_418a": "Tufelli_masonry_typeB",
            "Facade_418b": "Tufelli_masonry_typeD",
        },
    },
    "StructuralUnit_419": {
        "facades": {"Facade_419": "Tufelli_masonry_typeA"},
    },
    "StructuralUnit_420": {
        "facades": {"Facade_420": "Tufelli_masonry_typeD"},
    },
}

ADJACENT_UNIT_PAIRS = [
    ("StructuralUnit_417", "StructuralUnit_418"),
    ("StructuralUnit_418", "StructuralUnit_419"),
    ("StructuralUnit_419", "StructuralUnit_420"),
]


def hsto_ttl():
    lines = ["\n# --- HSTO: structural decomposition ---",
             "# Manuscript: \"quoined corners indicating originally detached buildings that",
             "# were later physically and structurally joined\" -> hsto:Quoin connections",
             "# between adjacent units. \"timber floors alla romana\" -> one hsto:TimberFloor",
             "# per unit (generic - not individually surveyed per unit).",
             "#",
             "# NOTE: the published ontology (read in full - see this file's module",
             "# docstring) has no object property linking a hsto:StructuralPart to the",
             "# hsto:Facade / hsto:HorizontalStructure instances that decompose it",
             "# (composition is presumably meant to be handled at the BEO/IFC spatial-",
             "# containment level, not duplicated in HSTO). Rather than force that",
             "# relationship through a property whose domain/range doesn't fit - which",
             "# would silently produce an invalid graph - unit/facade/floor membership is",
             "# recorded only as an rdfs:comment below. hsto:isConnectedTo (used further",
             "# down for the Quoin individuals) is correctly typed for this: its range is",
             "# hsto:Connection, and hsto:Quoin is a Connection subclass.",
             ""]

    for unit, data in STRUCTURAL_UNITS.items():
        facade_list = ", ".join(data["facades"].keys())
        lines.append(f':{unit} a hsto:StructuralPart ;')
        lines.append(f'    rdfs:comment "Decomposed into facades {facade_list} and one timber '
                      f'floor ({unit}_Floor) - no HSTO composition property for this, see note above" .')
        lines.append(f':{unit}_Floor a hsto:TimberFloor ;')
        lines.append(f'    rdfs:comment "Generic - manuscript describes \'timber floors alla romana\' '
                      f'for the aggregate, not surveyed per unit" .')
        lines.append("")
        for facade, masonry_type in data["facades"].items():
            lines.append(f':{facade} a hsto:Facade ;')
            lines.append(f'    rdfs:label "{facade}" ;')
            lines.append(f'    hsto:isMadeOf :{masonry_type} .')
        lines.append("")

    # Quoins between adjacent units (manuscript evidence, adjacency order
    # inferred from the cadastral map - see docstring above)
    for a, b in ADJACENT_UNIT_PAIRS:
        qname = f'Quoin_{a}_{b}'
        lines.append(f':{qname} a hsto:Quoin ;')
        lines.append(f'    rdfs:comment "Corner connection between {a} and {b} - manuscript '
                      f'evidence for quoined corners generally in this aggregate; which specific '
                      f'pair of units this quoin sits between is inferred from cadastral-map row '
                      f'order, not individually confirmed on site" .')
        lines.append(f':{a} hsto:isConnectedTo :{qname} .')
        lines.append(f':{b} hsto:isConnectedTo :{qname} .')
        lines.append("")

    # One historic opening, directly observed (A-419/a419: stone arch over
    # the door - see masonry_classification.json's typeA evidence)
    lines.append(':HistoricOpening_419Door a hsto:HistoricOpening ;')
    lines.append('    rdfs:comment "Door opening with dressed stone arch, A-419/a419 photos" .')
    lines.append(':Facade_419 hsto:hasHistoricOpening :HistoricOpening_419Door .')
    lines.append("")

    return "\n".join(lines)


def write_ttl(results, path):
    with open(path, "w", encoding="utf-8") as f:
        f.write(TTL_HEADER)
        for name, r in results.items():
            f.write(masonry_wall_ttl(name, r))
        f.write(hsto_ttl())


# ft/fc ratio, not derived from HMO (which has no tensile-strength rule at
# all - see write_material_database's docstring) but from PROJECT_BRIEF.md's
# own Chapter 6 (SERA-AIMS) reference masonry: ft=0.17 MPa at fc=1.30 MPa,
# i.e. ft/fc = 0.1308. Chosen over leaving tensile_strength at 0 because 0
# is not inert downstream: traced core.opensees_generation.model_builder
# .create_plastic_damage_elements -> models.damage_law.ConstitutiveLaws
# .ExponentialSoftening_Tension.tension(E, ft=0, Gt, side_length) and ran it
# (see chat log) - with ft=0 the loop's own convergence check
# (`if stress > s0*0.05`) is `0 > 0`, False on the first iteration, so the
# function returns a degenerate two-point curve Te=[0,0.0], Ts=[0,0],
# Td=[0,0] instead of an actual softening branch. That gets passed straight
# into `nDMaterial('ASDConcrete3D', ..., '-Te', 0, 0.0, ...)` - "not
# derived by HMO" silently becomes "asserted zero tensile strength" with no
# distinction between the two. A nonzero, sourced estimate avoids that.
TENSILE_TO_COMPRESSIVE_RATIO = 0.17 / 1.30


def write_material_database(results, path):
    """Field-compatible with core.ifc_processing.data_extractor.Material:
    name, density, young_modulus, poisson_ratio, is_structural,
    material_model_type, compressive_strength, tensile_strength,
    compression_fracture_energy, tensile_fracture_energy,
    compressive_elastic_behaviour.

    HMO derives compressive strength but not tensile strength (no SWRL rule
    for it at all, checked - not merely a gap in this script). tensile_strength
    here is compressive_strength * TENSILE_TO_COMPRESSIVE_RATIO (see that
    constant's comment for why 0 was rejected, not just "improved").
    compression/tensile_fracture_energy are left at 0, which - unlike
    tensile_strength - is not a placeholder without consequence either way:
    create_plastic_damage_elements already falls back to
    Gc = 15 + 0.43*fc - 0.0036*fc^2 and Gt = 0.025*(fc/10)^0.7 (Bazant,
    cited there) when the material's own values are 0, so leaving them at 0
    activates an existing, deliberate fallback rather than leaving a gap.

    Shear strength (Turnsek-Cacovic, computed by hmo_mqi.py) is NOT a
    Material field - core.ifc_processing.data_extractor.Material has no
    such attribute, and create_plastic_damage_elements has no shear-strength
    parameter to receive it (ASDConcrete3D's shear behaviour emerges from
    the triaxial damage-plasticity formulation itself, not from an explicit
    input). Kept in the JSON under the "_shear_strength_turnsek_cacovic_MPa"
    key for traceability, but load_material_objects (utils/dict_helper.py)
    deliberately excludes every "_"-prefixed key from the Material() call,
    so it is inert as far as element creation goes - documentation, not a
    live input.
    """
    db = {}
    for name, r in results.items():
        mech = r["mechanical_properties"]
        fc = mech["compressive_strength_MPa"]
        db[name] = {
            "name": name,
            "density": mech["mass_density_kg_m3"],
            "young_modulus": mech["young_modulus_MPa"],
            "poisson_ratio": 0.2,  # literature default for masonry, not MQI-derived - HMO has no rule for it
            "is_structural": True,
            "material_model_type": "PlasticDamage",
            "compressive_strength": fc,
            "tensile_strength": round(fc * TENSILE_TO_COMPRESSIVE_RATIO, 3),
            "compression_fracture_energy": 0,
            "tensile_fracture_energy": 0,
            "compressive_elastic_behaviour": 0,
            "_mqi_total": r["mqi_total"],
            "_shear_modulus_MPa": mech["shear_modulus_MPa"],
            "_shear_strength_turnsek_cacovic_MPa": mech["shear_strength_turnsek_cacovic_MPa"],
            "_evidence": r["evidence"],
            "_flags": r["flags"],
        }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(CLASSIFICATION_PATH) as f:
        classification = json.load(f)

    results = compute_all(classification)
    print_summary(results)

    write_ttl(results, os.path.join(OUT_DIR, "hmo_graph.ttl"))
    write_material_database(results, os.path.join(OUT_DIR, "material_database.json"))
    print(f"\nWrote {OUT_DIR}/hmo_graph.ttl and {OUT_DIR}/material_database.json")


if __name__ == "__main__":
    main()
